### PR TITLE
Adding clasp && publish as a lib

### PR DESCRIPTION
**Pull request by oshliaer**
@huan  please share for me <ai@contributor.pw> your google account. I'll make you as an owner of the library.

### CODE REVIEW

**Comment by oshliaer** [comment]
Also #16

**Review by huan — CHANGES_REQUESTED** [review]
Thanks for the PR!

I have a couple of questions:

1. What is .clasp.json, could you explain it briefly?
1. I saw there's two .clasp.json, one is in the root and another in the config/ directory. Does this necessary?
1. I saw a .class.json.bak; please remove it if it is useless.
1. What's the appscript.json for, could you please explain it two?
1. I saw a directory of `dist/`. Does that can generate automatically? If so, we should remove it and add it to the .gitignore, with a script to generate it automatically.
1. dist/appscript.json, too.
1. dist/gas-tap-lib.js, too.
1. Please remote the package-lock.json, it always causes the problem, and I believe we do not need it.
1. Please keep the example in the src/gas-tap-lib.js, because I believe someone might need it
1. And, please add some document about the clasp tool in the README, so that we can learn how to get started with it.

Please following my reviews, and I would love to merge this PR after we are all good with it.

**Comment by oshliaer** [comment]
1. `.clasp.json` is a config file for @google/clasp https://github.com/google/clasp. It's like node-google-apps-script. `.clasp.json` must be at the root of the npm project. 
1. I did as your application. In fact, the config folder may not be used. It really is not needed. Should I do this?
1. See todo below
1. appscript.json is a manifest file of Google Apps Script project https://developers.google.com/apps-script/concepts/manifests. `appscript.json` must be at the root of the google apps script project.  
1. See todo below
1. See todo below
1. See todo below
1. See todo below
1. Sorry. We have to come up with something else. The text has the word `UrlFetchApp`. It requires user permissions for additional scopes. And this is not always necessary. We can replace with `this['UrlFetch'+'App']`, but this is not clear.
1. See todo below

- [x] Remove backups files
- [x] Ignore `dist`
- [x] Ignore `package-lock.json`
- [x] Update README with `clasp`

**Comment by oshliaer** [comment]
@huan 

Check it again, please.

Cheers!

**Comment by huan** [comment]
Hi, Alex,

Thank you very much for the updates on this PR!

I'm sorry for the slow response because I really busy those weeks, and this PR is not short so that it will take me a little while to review.

Will try my best to make feedback this week.

**Comment by gbatra17** [comment]
any updates on this?

**Comment by oshliaer** [comment]
So bad. It's my md linter :imp:

**Pull request closed without merging**
